site_name: Technical Writing Portfolio
theme:
  name: material
nav:
  - Home: index.md
  - Operations & SOPs: sop-guide.md
  - GitHub Quickstart: github-guide.md
  - Enterprise Confluence: confluence-guide.md
  - Release Notes: changelog.md
  - API Reference: api-guide.md
